WebApplication2/Models/Paging.cs
using Microsoft.AspNetCore.Mvc.Rendering;

namespace WebApplication2.Models
{
    public class Paging
    {
        public int TotalItems { get; set; }
        public int CurrentPage { get; set; }
        public int PageSize { get; set; }
        public int TotalPages { get; set; }
        public int StartPage { get; set; }
        public int EndPage { get; set; }
        public string CurrentTable { get; set; }
        public Paging()
        {               }

        public Paging(int totalItems, int currentPage, int pageSize=10)
        {
            int totalPages = (int)Math.Ceiling((decimal)totalItems / pageSize);
            int startPage = currentPage - 5;
            int endPage = currentPage + 4;

            if (startPage <= 0){
                endPage = endPage - (startPage - 1);
                startPage = 1;
            }
            if (endPage > totalPages){
                endPage = totalPages;
                if (endPage > 10)
                {
                    startPage = endPage - 9;
                }
            }
            TotalItems = totalItems;
            CurrentPage = currentPage;
            PageSize = pageSize;
            StartPage = startPage;
            EndPage = endPage;
            TotalPages = totalPages;
        }
    }
}

WebApplication2/Controllers/StationController.cs
using ClosedXML.Excel;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebApplication2.DataObjects;
using WebApplication2.Models;

namespace WebApplication2.Controllers
{
    public class StationController : Controller
    {
        private readonly animal_shelter_testContext _context;

        public StationController(animal_shelter_testContext context)
        {
            _context = context;
        }
        public IActionResult Index(int pg = 1)
        {
            const int pageSize = 10;

            if (pg < 1)
                pg = 1;

            int recsCount = _context.Stations.Count();

            var paging = new Paging(recsCount, pg, pageSize);
            paging.CurrentTable = this.ControllerContext.RouteData.Values["controller"].ToString();

            int recSkip = (pg - 1) * pageSize;

            List<Station> stations = _context.Stations.Skip(recSkip).Take(paging.PageSize).ToList();

            this.ViewBag.Paging = paging;
            return View(stations);

        }

        [HttpGet]
        public IActionResult Create()
        {
            if (DB.status != "guest" && DB.status != "client")
            {
                Station station = new Station();
                return View(station);
            }
            return RedirectToAction("Index");
        }

        [ValidateAntiForgeryToken]
        [HttpPost]
        public IActionResult Create(Station station)
        {
            _context.Add(station);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            if (DB.status != "guest" && DB.status != "client")
            {
                Station station = _context.Stations.Find(id);
                return View(station);
            }
            return RedirectToAction("Index");
        }

        [ValidateAntiForgeryToken]
        [HttpPost]
        public IActionResult Edit(Station station)
        {
            _context.Attach(station);
            _context.Entry(station).State = EntityState.Modified;
            _context.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Delete(int id)
        {
            if (DB.status != "guest" && DB.status != "client")
            {
                Station station = _context.Stations.Find(id);
                return View(station);
            }
            return RedirectToAction("Index");
        }

        [ValidateAntiForgeryToken]
        [HttpPost]
        public IActionResult Delete(Station station)
        {
            try
            {
                _context.Attach(station);
                _context.Entry(station).State = EntityState.Deleted;
                _context.SaveChanges();
            }
            catch (Exception e)
            {
                _context.Entry(station).Reload();
                ModelState.AddModelError("", "Перед удалением станции необходимо, чтобы на нее не ссылались зависимые элементы (работники, животные и т.д.)");
                return View(station);
            }
            return RedirectToAction("Index");
        }

        public IActionResult Details(int id)
        {
            Station station = _context.Stations.Find(id);
            return View(station);
        }


        [HttpGet]
        public IActionResult CreateModalForm()
        {
            Station station = new Station();
            return PartialView("_CreateModalForm", station);
        }

        [HttpPost]
        public IActionResult CreateModalForm(Station station)
        {
            _context.Add(station);
            _context.SaveChanges();
            return NoContent();
        }

        public IActionResult ExportExcel()
        {
            var animals = _context.Stations.ToList();
            using (XLWorkbook wb = new XLWorkbook())
            {
                wb.Worksheets.Add(DB.ToDataTable(animals.ToList()));
                using (MemoryStream stream = new MemoryStream())
                {
                    wb.SaveAs(stream);
                    return File(stream.ToArray(), "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "stations.csv");
                }
            }
            return View();
        }
    }
}

WebApplication2/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ClosedXML.Excel;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebApplication2.DataObjects;
using WebApplication2.Models;

namespace WebApplication2.Controllers
{
    public class UsersController : Controller
    {
        private readonly animal_shelter_testContext _context;

        public UsersController(animal_shelter_testContext context)
        {
            _context = context;
        }

        // GET: Users
        public async Task<IActionResult> Index(int pg = 1)
        {
            if (DB.status == "admin" || DB.status == "director")
            {
                const int pageSize = 10;

                if (pg < 1)
                    pg = 1;

                int recsCount = _context.Users.Count();

                var paging = new Paging(recsCount, pg, pageSize);
                paging.CurrentTable = this.ControllerContext.RouteData.Values["controller"].ToString();

                int recSkip = (pg - 1) * pageSize;

                List<User> animals = _context.Users.Skip(recSkip).Take(paging.PageSize).ToList();

                this.ViewBag.Paging = paging;
                return View(animals.OrderBy(a => a.UserId));
            }
            return Redirect("~/Home/Index");
        }

        // GET: Users/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (DB.status == "admin" || DB.status == "director")
            {
                if (id == null || _context.Users == null)
                {
                    return NotFound();
                }

                var user = await _context.Users
                    .FirstOrDefaultAsync(m => m.UserId == id);
                if (user == null)
                {
                    return NotFound();
                }

                return View(user);
            }
            return Redirect("~/Home/Index");
        }

        // GET: Users/Create
        public IActionResult Create()
        {
            if (DB.status == "admin" || DB.status == "director")
            {
                return View();
            }
            return Redirect("~/Home/Index");
        }

        // POST: Users/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("UserId,Login,Password,Email,Level")] User user)
        {
            if (ModelState.IsValid)
            {
                _context.Add(user);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(user);
        }

        // GET: Users/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (DB.status == "admin" || DB.status == "director")
            {
                if (id == null || _context.Users == null)
                {
                    return NotFound();
                }

                var user = await _context.Users.FindAsync(id);
                if (user == null)
                {
                    return NotFound();
                }
                return View(user);
            }
            return Redirect("~/Home/Index");
        }

        // POST: Users/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("UserId,Login,Password,Email,Level")] User user)
        {
            if (id != user.UserId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(user);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UserExists(user.UserId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(user);
        }

        // GET: Users/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (DB.status == "admin" || DB.status == "director")
            {
                if (id == null || _context.Users == null)
                {
                    return NotFound();
                }

                var user = await _context.Users
                    .FirstOrDefaultAsync(m => m.UserId == id);
                if (user == null)
                {
                    return NotFound();
                }

                return View(user);
            }
            return Redirect("~/Home/Index");
        }

        // POST: Users/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Users == null)
            {
                return Problem("Entity set 'animal_shelter_testContext.Users'  is null.");
            }
            var user = await _context.Users.FindAsync(id);
            if (user != null)
            {
                _context.Users.Remove(user);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool UserExists(int id)
        {
            return (_context.Users?.Any(e => e.UserId == id)).GetValueOrDefault();
        }

        private bool UserExists(string login)
        {
            return (_context.Users?.Any(e => e.Login == login)).GetValueOrDefault();
        }



        public IActionResult Registration()
        {
            return View();
        }

        // POST: Users/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Registration([Bind("UserId,Login,Password,Email,Level")] User user)
        {
            user.Level = "client";
            if (!UserExists(user.Login) && ModelState.IsValid)
            {
                _context.Add(user);
                await _context.SaveChangesAsync();
                RedirectToAction("Login");
            }
            ModelState.AddModelError("", "Пользователь с таким логином уже существует!");
            return View(user);
        }


        public IActionResult Login()
        {
            return View();
        }

        // POST: Users/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        public async Task<IActionResult> Login([Bind("UserId,Login,Password, Level")] User user)
        {
            if (UserExists(user.Login))
            {
                if (_context.Users.Any(a => a.Login == user.Login && a.Password == user.Password))
                {
                    DB.status = _context.Users.First(a => a.Login == user.Login).Level;

                    return Redirect("~/Home/Index");
                }
                else
                {
                    ModelState.AddModelError("", "Неверный пароль!");
                    return View(user);
                }
            }
            ModelState.AddModelError("", "Неверный логин!");
            return View(user);

        }

        public IActionResult Logout()
        {
            DB.status = "guest";
            return Redirect("~/Home/Index");
        }

        public IActionResult ExportExcel()
        {
            var animals = _context.Users.ToList();
            using (XLWorkbook wb = new XLWorkbook())
            {
                wb.Worksheets.Add(DB.ToDataTable(animals.ToList()));
                using (MemoryStream stream = new MemoryStream())
                {
                    wb.SaveAs(stream);
                    return File(stream.ToArray(), "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "users.csv");
                }
            }
            return View();
        }
    }
}

WebApplication2/Views/Shared/_CreateModalDialog.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<div id="DivCreateDialogHolder" class="modal fade text-width: 30%;"
    role="dialog">

    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-headers">
                <h2>Создать</h2>
                <button type="button" class="close" data-bs-dismiss="modal">&times;</button>
            </div>

            <div id="DivCreateDialog" class="modal-body">
            </div>


            <div class="modal-footer">


                <div class="btn-group">
                    <div>
                        <button id="dupBackBtn" type="button" class="btn btn-danger" data-icon="back" data-sb-dismiss="modal">Назад</button>
                    </div>
                    <div class="ml-4">
                        <input id="dupSubmitBtn" type="button" value="Сохранить" class="btn btn-primary"
                                onclick="submitModalForm()"/>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

WebApplication2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<div class="layout_main">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>@ViewData["Title"] - WebApplication2</title>


        @*    <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=Edge">
        <meta name="description" content="">
        <meta name="keywords" content="">
        <meta name="author" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

        <link rel="stylesheet" href="css/bootstrap.min.css">
        <link rel="stylesheet" href="css/font-awesome.min.css">
        <link rel="stylesheet" href="css/aos.css">
        <link rel="stylesheet" href="css/owl.carousel.min.css">
        <link rel="stylesheet" href="css/owl.theme.default.min.css">

        <!-- MAIN CSS -->
        <link rel="stylesheet" href="css/templatemo-digital-trend.css">*@


        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
        <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
        <link rel="stylesheet" href="~/WebApplication2.styles.css" asp-append-version="true" />
        <script src="https://kit.fontawesome.com/0e84072b0c.js" crossorigin="anonymous"></script>
    </head>
    <body>
        <header>
            <nav class="navbar navbar-expand-sm navbar-nav-scroll navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
                <div class="container-fluid">
                    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><i class="fa fa-paw fa-2x"></i> ССП <br> ZOOHELP</a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="navbar-collapse collapse d-sm-inline-flex justify-content-center">
                        <ul class="navbar-nav">

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Station" asp-action="Index">Станции</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Animal" asp-action="Index">Животные</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="AnimalTypes" asp-action="Index">Виды животных</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="VolunteerGroups" asp-action="Index">Волонтерские группы</a>
                            </li>

                            @if (DB.status != "guest" && DB.status!="client")
                            {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="CarrierVolunteers" asp-action="Index">Волонтеры-перевозчики</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Volunteers" asp-action="Index">Волонтеры</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="VolunteerOrganizations" asp-action="Index">Волонтерские организации</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="VolunteerApplications" asp-action="Index">Волонтерские заявки</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="AnimalApplications" asp-action="Index">Заявки на животных</a>
                            </li>
                            }

                            @if (DB.status == "admin" || DB.status == "director")
                            {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Workers" asp-action="Index">Работники</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Donations" asp-action="Index">Пожертвования</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="DonationTypes" asp-action="Index">Виды пожертвований</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Donators" asp-action="Index">Благотворители</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="Index">Пользователи</a>
                            </li>
                            }

                        
                        
                    @*<li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                    </li>*@
                    </ul>
                        
                </div>
                    <div style="justify-content: right; align-self: end; align-content:center;">
                        @if(DB.status=="guest")
                        {
                        <a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="Registration">Регистрация</a>
                            <a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="Login">Авторизация</a>
                        }
                        else
                        {
                            <a class="nav-link text-dark">@DB.RuLang[DB.status]</a>
                            <a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="Logout" >Выход</a>
                        }
                    </div>
                </div>
            </nav>
        </header>


        <div class="wrapper">
            <div class="pull-left">
                <main role="main" >


                    @*<partial name="_CreateModalDialog" />*@

                    @RenderBody()
                </main>
            </div>
        </div>

        <div class="description">
            <header>
                
            </header>
        </div>

        <div class="for_footer">
            <footer class="footer text-muted">
                <div class="container">
                    &copy; 2023 - НИУ ВШЭ - Пермь, Кирьянов Сергей, ПИ-21-3
                </div>
            </footer>
        </div>
        <script src="~/lib/jquery/dist/jquery.min.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
        @await RenderSectionAsync("Scripts", required: false)
    </body>
</div>
</html>

WebApplication2/Views/Shared/_Paging.cshtml
@model WebApplication2.Models.Paging
<div class="container">
	@if (Model.TotalPages > 0)
	{
		<ul class="pagination justify-content-end">
			@if (Model.CurrentPage>1)
			{
				<li class="page-item">
					<a class="page-link" asp-controller="@Model.CurrentTable" asp-action="Index" asp-route-pg="1"><i class="fa fa-angle-double-left fa-lg"></i></a>
				</li>
				<li>
					<a class="page-link" asp-controller="@Model.CurrentTable" asp-action="Index" asp-route-pg="@(Model.CurrentPage-1)"><i class="fa fa-angle-left fa-lg"></i></a>
				</li>
			}
			@for (var pge = Model.StartPage; pge <=Model.EndPage; pge++)
			{
				<li class="page-item @(pge == Model.CurrentPage ? "active" : "")">
					<a class="page-link" asp-controller="@Model.CurrentTable" asp-action="Index" asp-route-pg="@pge">@pge</a>
				</li>
			}
			@if (Model.CurrentPage < Model.TotalPages)
			{
				<li class="page-item">
					<a class="page-link" asp-controller="@Model.CurrentTable" asp-action="Index" asp-route-pg="@(Model.CurrentPage+1)"><i class="fa fa-angle-right fa-lg"></i></a>
				</li>
				<li>
					<a class="page-link" asp-controller="@Model.CurrentTable" asp-action="Index" asp-route-pg="@(Model.TotalPages)"><i class="fa fa-angle-double-right fa-lg"></i></a>
				</li>
			}
		</ul>
	}
</div>